CREATE TABLE method (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE place (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE category (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE transactions (id INTEGER PRIMARY KEY, date INTEGER, mid INTEGER, pid INTEGER, cid INTEGER, pence INTEGER, comment TEXT);
